name: syft-sbom-ci

on:
  push:

jobs:
  syft-sbom:

    runs-on: ubuntu-latest
    env:
      VERSION: "v1.2.3"
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Create dist dir
      run: mkdir dist

    - name: Anchore SBOM Action
      uses: anchore/sbom-action@v0.12.0
      with:
        artifact-name: "k6-${VERSION}-spdx.json"
        upload-release-assets: false
        output-file: "dist/k6-${VERSION}-spdx.json"
    - name: Checking
      run: ls -la; pwd; ls -la dist
