name: syft-sbom-ci

on:
  push:

jobs:
  syft-sbom:

    runs-on: ubuntu-latest
    env:
      VERSION: "v1.2.3"
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Create dist dir
      run: mkdir dist; cd dist

    - name: Anchore SBOM Action
      continue-on-error: true
      uses: anchore/sbom-action@v0.12.0
      with:
        artifact-name: k6-${{ env.VERSION }}-spdx.json
        upload-release-assets: false1
        output-file: dist1/k6-${{ env.VERSION }}-spdx.json
    - name: Checking
      run: ls -la; pwd; ls -la dist
