name: syft-sbom-ci

on:
  push:

jobs:
  syft-sbom:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
        
    - name: Anchore SBOM Action
      uses: anchore/sbom-action@v0.12.0
      with:
         artifact-name: ${{ github.event.repository.name }}-spdx.json
         upload-artifact: false
         upload-release-assets: false
         output-file: dist
    - name: Checking
      run: ls -la; pwd
