name: syft-sbom-ci

on:
  push:

jobs:
  syft-sbom:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Create dist dir
      run: mkdir dist

    - name: Anchore SBOM Action
      uses: anchore/sbom-action@v0.12.0
      with:
         artifact-name: test-spdx.json
         # upload-artifact: false
         # upload-release-assets: false
         output-file: dist/test-spdx.json
    - name: Checking
      run: ls -la; pwd; ls -la dist
